#!/bin/sh

echo "Running pre-commit hook..."

FILES_CHANGED_BEFORE=$(git status --porcelain)

# Run lint-staged for code formatting and linting
echo "Running lint-staged for code formatting and linting..."

npx lint-staged

FILES_CHANGED_AFTER=$(git status --porcelain)

# Check if any files have changed after formatting
if [ "$FILES_CHANGED_BEFORE" != "$FILES_CHANGED_AFTER" ]; then
  echo ""
  echo "👉 Code formatting made changes! Please review and commit again."
  echo "🚫 Commit aborted."
  exit 1
fi

echo "✅ Pre-commit checks passed! Proceeding with commit."
